source 'https://rubygems.org'

gem 'rails',              '4.1.1'
gem 'sqlite3',            '1.3.9'
gem 'sass-rails',         '4.0.3'
gem 'jquery-rails',       '3.1.1'
gem 'turbolinks',         '2.2.2'
gem 'uglifier',           '2.5.1'
gem 'pry',                '0.9.12'
gem 'pry-nav',            '0.2.2'
gem 'pry-stack_explorer', '0.4.9'
gem 'pry-rails',          '0.2.2'
gem 'slim-rails',         '2.1.5'
gem 'coffee-rails',       '4.0.1'
gem 'therubyracer',       '0.12.1', platforms: :ruby
